export const SET_SETTINGS = 'SET SETTINGS';
export const SET_INITIAL_SETTINGS = 'SET INITIAL SETTINGS';
export const SET_DEFAULT_SETTINGS = 'SET DEFAULT SETTINGS';
export const RESET_DEFAULT_SETTINGS = 'RESET DEFAULT SETTINGS';

export const OPEN_FOLDED_NAVBAR = '[NAVBAR] OPEN FOLDED';
export const CLOSE_FOLDED_NAVBAR = '[NAVBAR] CLOSE FOLDED';

export const TOGGLE_FOLDED_NAVBAR = '[NAVBAR] TOGGLE FOLDED';

export const TOGGLE_MOBILE_NAVBAR = '[NAVBAR] TOGGLE MOBILE';
export const OPEN_MOBILE_NAVBAR = '[NAVBAR] OPEN MOBILE';
export const CLOSE_MOBILE_NAVBAR = '[NAVBAR] CLOSE MOBILE';

export const GET_NAVIGATION = '[NAVIGATION] GET NAVIGATION';
export const SET_NAVIGATION = '[NAVIGATION] SET NAVIGATION';
export const RESET_NAVIGATION = '[NAVIGATION] RESET NAVIGATION';
