//SIGN-In actions
export const SIGNIN = "SIGNIN";
export const SIGNINLOADING = "SIGNINLOADING";
export const SIGNINSUCCESS = "SIGNINSUCCESS";
export const SIGNINERROR = "SIGNINERROR";
export const CLEARSIGNINSTATE = "CLEARSIGNINSTATE";

//SIGN-Up actions
export const SIGNUP = "SIGNUP";
export const SIGNUPLOADING = "SIGNUPLOADING";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPERROR = "SIGNUPERROR";
export const CLEARSIGNUPSTATE = "CLEARSIGNUPSTATE";

//Products actions
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

//Upload actions
export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
export const UPLOAD_PRODUCT_DATA = "UPLOAD_PRODUCT_DATA";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const FETCH_PRODUCT_BY_COLLECTION = "FETCH_PRODUCT_BY_COLLECTION";
